@extends('layout.app')
@section('content')
@include('includes.header')
@include ('includes.home.hero')
@include ('includes.home.details-home')
@include ('includes.home.adocao')
@include ('includes.home.timelineHome')
@include ('includes.home.faq')
@include ('includes.home.depoimentos')
@include ('includes.home.clientes')
@include('includes.home.footerHome')
@include ('includes.modal')
@include ('includes.cookies')
@stop