@extends('layout.app')
@section('content')
@include('includes.header')
@include('includes.sobre.heroSobre')
@include('includes.sobre.timelineSobre')
@include('includes.sobre.estrutura')
@include('includes.sobre.missao')
@include('includes.footerGeral')
@stop